### ISSUE TITLE
[nextpnr-fpga-interchange] Site PIPs routing issue

### ISSUE THREAD

**Issue by mtdudek** [YosysHQ/nextpnr#829]
When creating bitstream from dcp for murax using fpga-interchag-tests I got error in vivado when site PIP used C5LUT and LUTRAM used C6LUT. I looked deeper into this and found out that:
* in Xilinx 7-series when ABCD6LUT is used as LUTRAM smaller 5LUTs cannot be used as site PIPs. They can only be used as LUTRAMs or shouldn't be used at all.

I think that main issue is that 6LUTs and 5LUTs aren't independent from each other and only point where it is represented is 
constraint file, but constrains are only checked for cells placements and not for site PIPs.
Maybe we could add constraints for site PIPs with format like:
```
- sitepip:
  - locations:
    - siteType: [ABC]
      bel:
        bels:
          - x
          - y
          - z
      implies:
        - tag: EF
          state: HI
```

This would fix this issue, but will require more configuration data per used architecture, but only when it's necessary.

I'm attaching DCP file, logical and physical netlist in capnp format as well as physical netlst in yaml format.
[murax.zip](https://github.com/YosysHQ/nextpnr/files/7243303/murax.zip)
